// Branded SVG icons. Some use `currentColor` (utility icons that inherit from
// the surrounding text) and some carry a multi-colour palette baked in (the
// "branded" nav icons — IconHome, IconFiles, IconChat, etc.). Most render
// inside a 24×24 box and accept `className`.
//
// The set is the single source of truth for app glyphs across every
// `thefactory-*` consumer — desktop, web, and the upcoming mobile app. Don't
// keep a parallel icon set in a consumer.

export {
  IconFileBadge,
  IconFileDefault,
  IconFileImage,
  IconFileJson,
  IconFileText,
  IconFileZip,
} from './IconFileTypes'

export { IconAmbulance } from './IconAmbulance'
export { IconAntenna } from './IconAntenna'
export { IconArchive } from './IconArchive'
export { IconArrowDown } from './IconArrowDown'
export { IconArrowLeftMini } from './IconArrowLeftMini'
export { IconArrowRightMini } from './IconArrowRightMini'
export { IconArrowUp } from './IconArrowUp'
export { IconAttach } from './IconAttach'
export { IconBack } from './IconBack'
export { IconBandage } from './IconBandage'
export { IconBank } from './IconBank'
export { IconBarChart } from './IconBarChart'
export { IconBaseball } from './IconBaseball'
export { IconBasketball } from './IconBasketball'
export { IconBell } from './IconBell'
export { IconBlueprint } from './IconBlueprint'
export { IconBoard } from './IconBoard'
export { IconBrain } from './IconBrain'
export { IconBranch } from './IconBranch'
export { IconBricks } from './IconBricks'
export { IconBriefcase } from './IconBriefcase'
export { IconBug } from './IconBug'
export { IconBuild } from './IconBuild'
export { IconCalculator } from './IconCalculator'
export { IconCalendar } from './IconCalendar'
export { IconCapsule } from './IconCapsule'
export { IconCementMixer } from './IconCementMixer'
export { IconChartDown } from './IconChartDown'
export { IconChartUp } from './IconChartUp'
export { IconChat } from './IconChat'
export { IconCheckCircle } from './IconCheckCircle'
export { IconCheck } from './IconCheck'
export { IconCheckmarkCircle } from './IconCheckmarkCircle'
export { IconChevron } from './IconChevron'
export { IconChevronDown } from './IconChevronDown'
export { IconChevronLeft } from './IconChevronLeft'
export { IconChevronRight } from './IconChevronRight'
export { IconClamp } from './IconClamp'
export { IconClipboardCheck } from './IconClipboardCheck'
export { IconCopy } from './IconCopy'
export { IconClose } from './IconClose'
export { IconCode } from './IconCode'
export { IconCoins } from './IconCoins'
export { IconCollection } from './IconCollection'
export { IconCommit } from './IconCommit'
export { IconContract } from './IconContract'
export { IconCpu } from './IconCpu'
export { IconCrane } from './IconCrane'
export { IconCreditCard } from './IconCreditCard'
export { IconDatabase } from './IconDatabase'
export { IconDelete } from './IconDelete'
export { IconDna } from './IconDna'
export { IconDocument } from './IconDocument'
export { IconDollar } from './IconDollar'
export { IconDoubleUp } from './IconDoubleUp'
export { IconDumbbell } from './IconDumbbell'
export { IconEdit } from './IconEdit'
export { IconError } from './IconError'
export { IconExcavator } from './IconExcavator'
export { IconExclamation } from './IconExclamation'
export { IconEye } from './IconEye'
export { IconEyeOff } from './IconEyeOff'
export { IconFastMerge } from './IconFastMerge'
export { IconFileAdded } from './IconFileAdded'
export { IconFileDeleted } from './IconFileDeleted'
export { IconFileModified } from './IconFileModified'
export { IconFiles } from './IconFiles'
export { IconFirstAidKit } from './IconFirstAidKit'
export { IconFolder } from './IconFolder'
export { IconFolderOpen } from './IconFolderOpen'
export { IconFootball } from './IconFootball'
export { IconFunction } from './IconFunction'
export { IconGitHub } from './IconGitHub'
export { IconGlobe } from './IconGlobe'
export { IconGolf } from './IconGolf'
export { IconHammer } from './IconHammer'
export { IconHandshake } from './IconHandshake'
export { IconHardHat } from './IconHardHat'
export { IconHeadset } from './IconHeadset'
export { IconHeartPulse } from './IconHeartPulse'
export { IconHeartbeat } from './IconHeartbeat'
export { IconHockey } from './IconHockey'
export { IconHome } from './IconHome'
export { IconHospital } from './IconHospital'
export { IconHourglass } from './IconHourglass'
export { IconInfrastructure } from './IconInfrastructure'
export { IconKey } from './IconKey'
export { IconLightbulb } from './IconLightbulb'
export { IconList } from './IconList'
export { IconLoader } from './IconLoader'
export { IconLungs } from './IconLungs'
export { IconMaximize } from './IconMaximize'
export { IconMedicalCross } from './IconMedicalCross'
export { IconMegaphone } from './IconMegaphone'
export { IconMenu } from './IconMenu'
export { IconMerge } from './IconMerge'
export { IconMicroscope } from './IconMicroscope'
export { IconMinimize } from './IconMinimize'
export { IconMobile } from './IconMobile'
export { IconMoneyTransfer } from './IconMoneyTransfer'
export { IconMonitor } from './IconMonitor'
export { IconNotAllowed } from './IconNotAllowed'
export { IconPackage } from './IconPackage'
export { IconPalette } from './IconPalette'
export { IconPercent } from './IconPercent'
export { IconPieChart } from './IconPieChart'
export { IconPiggyBank } from './IconPiggyBank'
export { IconPill } from './IconPill'
export { IconPlay } from './IconPlay'
export { IconPlus } from './IconPlus'
export { IconPresentation } from './IconPresentation'
export { IconPullRequest } from './IconPullRequest'
export { IconPuzzle } from './IconPuzzle'
export { IconReceipt } from './IconReceipt'
export { IconRefresh } from './IconRefresh'
export { IconRefreshChat } from './IconRefreshChat'
export { IconRevert } from './IconRevert'
export { IconRobot } from './IconRobot'
export { IconRocket } from './IconRocket'
export { IconRunner } from './IconRunner'
export { IconSafetyVest } from './IconSafetyVest'
export { IconSave } from './IconSave'
export { IconScroll } from './IconScroll'
export { IconSearch } from './IconSearch'
export { IconSend } from './IconSend'
export { IconServer } from './IconServer'
export { IconSettings } from './IconSettings'
export { IconShield } from './IconShield'
export { IconShoppingCart } from './IconShoppingCart'
export { IconShovel } from './IconShovel'
export { IconSoccerBall } from './IconSoccerBall'
export { IconStethoscope } from './IconStethoscope'
export { IconStop } from './IconStop'
export { IconStopCircle } from './IconStopCircle'
export { IconStore } from './IconStore'
export { IconStretcher } from './IconStretcher'
export { IconSyringe } from './IconSyringe'
export { IconTarget } from './IconTarget'
export { IconTargetDollar } from './IconTargetDollar'
export { IconTennis } from './IconTennis'
export { IconTerminal } from './IconTerminal'
export { IconTestTube } from './IconTestTube'
export { IconTests } from './IconTests'
export { IconThermometer } from './IconThermometer'
export { IconThumbDown } from './IconThumbDown'
export { IconThumbUp } from './IconThumbUp'
export { IconTimeline } from './IconTimeline'
export { IconToolbox } from './IconToolbox'
export { IconTooth } from './IconTooth'
export { IconTrafficCone } from './IconTrafficCone'
export { IconUsers } from './IconUsers'
export { IconVolleyball } from './IconVolleyball'
export { IconWallet } from './IconWallet'
export { IconWarningTriangle } from './IconWarningTriangle'
export { IconWheelbarrow } from './IconWheelbarrow'
export { IconWorkspace } from './IconWorkspace'
export { IconWrench } from './IconWrench'
export { IconXCircle } from './IconXCircle'
