// Branded SVG icons. Some use `currentColor` (utility icons that inherit from
// the surrounding text) and some carry a multi-colour palette baked in (the
// "branded" nav icons — IconHome, IconFiles, IconChat, etc.). Both flavours
// render inside a 24×24 box and accept `className`.

export { IconAntenna } from './IconAntenna'
export { IconArchive } from './IconArchive'
export { IconArrowDown } from './IconArrowDown'
export { IconArrowLeftMini } from './IconArrowLeftMini'
export { IconArrowRightMini } from './IconArrowRightMini'
export { IconArrowUp } from './IconArrowUp'
export { IconAttach } from './IconAttach'
export { IconBack } from './IconBack'
export { IconBell } from './IconBell'
export { IconBoard } from './IconBoard'
export { IconBranch } from './IconBranch'
export { IconBug } from './IconBug'
export { IconCalculator } from './IconCalculator'
export { IconChat } from './IconChat'
export { IconCheckCircle } from './IconCheckCircle'
export { IconCheckmarkCircle } from './IconCheckmarkCircle'
export { IconChevron } from './IconChevron'
export { IconChevronDown } from './IconChevronDown'
export { IconChevronLeft } from './IconChevronLeft'
export { IconChevronRight } from './IconChevronRight'
export { IconClose } from './IconClose'
export { IconCode } from './IconCode'
export { IconCollection } from './IconCollection'
export { IconCommit } from './IconCommit'
export { IconDelete } from './IconDelete'
export { IconDoubleUp } from './IconDoubleUp'
export { IconEdit } from './IconEdit'
export { IconError } from './IconError'
export { IconExclamation } from './IconExclamation'
export { IconFastMerge } from './IconFastMerge'
export {
  IconFileBadge,
  IconFileDefault,
  IconFileImage,
  IconFileJson,
  IconFileText,
  IconFileZip,
} from './IconFileTypes'
export { IconFiles } from './IconFiles'
export { IconFolder } from './IconFolder'
export { IconFolderOpen } from './IconFolderOpen'
export { IconGlobe } from './IconGlobe'
export { IconHome } from './IconHome'
export { IconHourglass } from './IconHourglass'
export { IconLightbulb } from './IconLightbulb'
export { IconList } from './IconList'
export { IconLoader } from './IconLoader'
export { IconMenu } from './IconMenu'
export { IconPlay } from './IconPlay'
export { IconPlus } from './IconPlus'
export { IconPullRequest } from './IconPullRequest'
export { IconRefresh } from './IconRefresh'
export { IconRevert } from './IconRevert'
export { IconRobot } from './IconRobot'
export { IconSearch } from './IconSearch'
export { IconSend } from './IconSend'
export { IconNotAllowed } from './IconNotAllowed'
export { IconRefreshChat } from './IconRefreshChat'
export { IconScroll } from './IconScroll'
export { IconSettings } from './IconSettings'
export { IconStop } from './IconStop'
export { IconStopCircle } from './IconStopCircle'
export { IconTests } from './IconTests'
export { IconThumbDown } from './IconThumbDown'
export { IconThumbUp } from './IconThumbUp'
export { IconTimeline } from './IconTimeline'
export { IconToolbox } from './IconToolbox'
export { IconWarningTriangle } from './IconWarningTriangle'
export { IconWorkspace } from './IconWorkspace'
export { IconXCircle } from './IconXCircle'
